# Generated by Django 3.2.5 on 2021-11-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзину'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Продукт для корзины', 'verbose_name_plural': 'Продукт для корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователя'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AddField(
            model_name='product',
            name='image_b',
            field=models.ImageField(null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_l',
            field=models.ImageField(null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_r',
            field=models.ImageField(null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_t',
            field=models.ImageField(null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='sub_title',
            field=models.CharField(max_length=100, verbose_name='Под-заголовок'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
