# Generated by Django 3.2.5 on 2021-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211108_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_b',
            field=models.ImageField(default=1, help_text='Загружайте изображения стороны данного товара', upload_to='', verbose_name='Боковые изображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image_l',
            field=models.ImageField(help_text='Загружайте изображения стороны данного товара (необязательно)', null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_r',
            field=models.ImageField(help_text='Загружайте изображения стороны данного товара (необязательно)', null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_t',
            field=models.ImageField(default=1, help_text='Загружайте изображения стороны данного товара', upload_to='', verbose_name='Боковые изображения'),
            preserve_default=False,
        ),
    ]
