# Generated by Django 3.2.5 on 2021-11-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211108_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_r',
        ),
    ]
