# Generated by Django 3.2.5 on 2022-01-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211231_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_l',
            field=models.ImageField(help_text='Загружайте изображения стороны данного товара', null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_r',
            field=models.ImageField(help_text='Загружайте изображения стороны данного товара', null=True, upload_to='', verbose_name='Боковые изображения'),
        ),
    ]
